---
spring:
  profiles: default

---
spring.datasource.url: jdbc:postgresql://ec2-54-195-246-59.eu-west-1.compute.amazonaws.com:5432/d1uvs64rr2cg7m?sslmode=require
spring.datasource.username: ryddkcrqxvgjww
spring.datasource.password: b4a9fbfe262c2c9f031ac11e38fb2629685fcb3efa9acac46dd24352a7f4bb19
spring.datasource.driver-class-name: org.postgresql.Driver

---
spring:
  profiles: test

spring.jpa:
  hibernate:
    ddl-auto: update

---
spring:
  profiles: local

spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://mysql:3306/demo
  username: dbuser
  password: dbp4ss

spring.jpa:
  hibernate:
    dialect: org.hibernate.dialect.MySQLInnoDBDialect
    ddl-auto: update